### ISSUE TITLE
This is a question pertaining to sending mail; I am not raising an issue.

### ISSUE THREAD

**Issue by neela77777** [miguelgrinberg/flasky#112]
I am trying to send a password reset mail from the application, and I do not receive the email. 
I checked out the final version of flasky with celery.
I do not see any errors being reported.
Here are mail mail settings in the config.py file

    MAIL_SERVER = 'smtp.mail.yahoo.com'
    MAIL_PORT = 587
    MAIL_USE_TLS = True
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    CELERY_BROKER_URL = 'redis://localhost:6379/0'
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    FLASKY_MAIL_SUBJECT_PREFIX = '[Flasky]'
    FLASKY_MAIL_SENDER = 'Flasky Admin <name@yahoo.com>'

I set the MAIL_USERNAME and MAIL_PASSWORD in the environment.

Is there a way I can debug what is happening with mailing the password reset please?

Thank you.
Neela

**Comment by neela77777** [comment]
I solved this issue. But I am now getting this error ..

SMTPException: SMTP AUTH extension not supported by server.

Does anyone have an idea what this means?

Thank you.
Neela

**Comment by neela77777** [comment]
Interestingly, if I switch to a gmail account, then I am getting the following error:  "Username and Password not accepted"

The username and password work if I manually login.
This is becoming a bit of a puzzle.
Would appreciate any help.
Thank you.
Neela

**Comment by neela77777** [comment]
After more experimentation, one version worked. Thanks anyway.

**Comment by miguelgrinberg** [comment]
So these are different issues.

> SMTPException: SMTP AUTH extension not supported by server.

This is likely caused by a bad email server configuration. The server that you are using says it does not support authentication, yet your configuration indicates that you have to authenticate.

> "Username and Password not accepted"

This one on gmail could be related to a new security feature on gmail accounts that restrict third party cllients from connecting to the service using username and password. The gmail configuration page has a setting to allow third parties to connect.
