### ISSUE TITLE
Accessing config from models.py

### ISSUE THREAD

**Issue by joshmreesjones** [miguelgrinberg/flasky#120]
I'm in my own `models.py` trying to define a model for a question:

```
class Question(db.Model):
    title = db.Column(db.String(150))
```

However, I'd like to store this (and other configuration values relevant to database models) in `config.py` instead so I can do this:

```
from flask import current_app

class Question(db.Model):
    title = db.Column(db.String(current_app.config[MAX_QUESTION_TITLE_LENGTH]))
```

However, when I do that, this error occurs:

```
RuntimeError: working outside of application context
```

I read the documentation on the application context, but I'm not sure how to fix the problem. Is there a way to put these values in `config.py` or should I put them at the top of `models.py` instead?

**Comment by miguelgrinberg** [comment]
Somehow I missed this issue when it was posted. Sorry about that!

The problem is that you are associating a configurable value to the schema of your database, which is really not a good approach, since the configuration can change at any time and will not represent the state of your db schema. You should use a static value here, and if it needs to change, make the change through a database migration.
