### ISSUE TITLE
How to add a additional database query to each view?

### ISSUE THREAD

**Issue by imnisen** [miguelgrinberg/flasky#134]
Hi,
I am customizing flasky to add notification, I make a table called 'notification' to record someone@another, and I change the top navbar to add a "notification" link. 
My problem is, each time when user refresh the page, I need to check the "notification" table to see if current user has a notification,if someone has, set a different tag to notice user. However I don't want to put query in each view function and render it in the view, this is duplicate and tedious, I want to add to every request.
I think "after_request" method may help, but I don't know how to add variables like in the view function that needed in the template.

Any suggestions is appreciated!
Thanks for your attention!

**Comment by miguelgrinberg** [comment]
Well, the after_request might be too late, because at the time this handler gets called the page template has been rendered. 

A good option, in my opinion, is to add a `has_notifications()` method to the `User` class. Then in your `base.html` template where the navbar is defined, you can add a conditional statement to render the notification link when appropriate. Since the base template is referenced by all other templates, you need to do this only once, and it will automatically apply to all pages.

**Comment by imnisen** [comment]
Yeah! That works! Write a method in the User class. What I ignored is that **each view renders the "User" object**, so, if I add the method to the User class, that I can access in each view directly.

Thank you very much, really helps me!
