### ISSUE TITLE
Question: Chapter 12

### ISSUE THREAD

**Issue by Mohamad1994HD** [miguelgrinberg/flasky#135]
![12313](https://cloud.githubusercontent.com/assets/11790718/14866892/883d24a8-0cce-11e6-96bc-a1ca9816c235.png)

I have difficulty in understanding the following concepts:

1) What is the 'lazy' doing when we say 'joined' or 'dynamic', what I can understand its for refinement of the query result since dynamic will allow filtering? that what I could understand from the book and from online docs.. can it be explained a little bit more pls

2) What is the query object, what I know from SQL is when I run a query it will return values or items, so what could the object in mean is it the SELECT statement with the followed conditions? 

3) in the cascade='all, delete orphan' it means that for all records delete the related objects ? if I got it wrong pls help

Thanks in advance

**Comment by miguelgrinberg** [comment]
1) "lazy" specifies how SQLAlchemy should work with the relationship. A value of "dynamic" means that the relationship should not be included in the query for the parent resource. Instead, the query for the relationship should be left as the value of the property, so that you can manually trigger the query as needed. A value of "joined" means that when the parent resource is queried, a join should be issued to query the related resource(s) in the same query.

2) In SQLAlchemy, a query object holds all the information necessary to run a query and return the results as Python objects. Its basic function is to translate between the Python and the database domains in a mostly transparent way.

3) No. the "all, delete-orphan" cascade means that when a resource on the other side of the relationship is deleted, this resource should be deleted as well.

Not sure if you know, but SQLAlchemy has pretty good documentation, which should answer these and any other questions you may have. http://sqlalchemy.org.

**Comment by Mohamad1994HD** [comment]
thanks alot
