### ISSUE TITLE
How to recreate development database at the end of ch 9?

### ISSUE THREAD

**Issue by priyankamandikal** [miguelgrinberg/flasky#152]
At the end of ch9, it is mentioned that we need to recreate/update the db. How do we update it? 
Do I just have to open the manage.py python shell and run:
`Role.insert_roles()`
Do I need to explicitly assign roles to users in the shell? If so, what is the command for that?
And then I run the following in the terminal:
`python manage.py db migrate`
`python manage.py db upgrade`

In case I want to recreate the entire db, how do I do it?

**Comment by miguelgrinberg** [comment]
To insert the roles in the database, just call `Role.insert_roles()` from a shell, like you said.

To update existing users and give them a role, also do it in the shell. Just load the users, set a role in them, and write them back to the database. For example, to assign the default role to a user, load the user and then run `user.role = Role.query.filter_by(default=True).first()`.

To start from scratch with a new database, delete the database file from disk, then run `python manage.py db upgrade`, then start a shell and run `Role.insert_roles()`.

This process is going to be automated later on, by the way, so keep reading :)

**Comment by priyankamandikal** [comment]
Okay, so while coding this out on my own,I have everything before 9a is in the master branch.
For testing the roles functionality in 9a, I have a new branch called 'roles'.

As suggested, I deleted the data-dev.sqlite and recreated the db while in master. I then switched to roles, and upgraded the db, to get the following error:
```
"No support for ALTER of constraints in SQLite dialect")
NotImplementedError: No support for ALTER of constraints in SQLite dialect
```

I don't know where I am going wrong. 
Also, what is the difference between a migrate and upgrade? When should I perform the former?

**Comment by miguelgrinberg** [comment]
SQLite is a fairly limited database in terms of migrating tables. What you are seeing is an error due to this limitation. If you do this using MySQL or Postgres you will not have this error.

Basically SQLite does not implement the ALTER SQL command to modify existing columns, it only supports adding new columns.

**Comment by priyankamandikal** [comment]
Oh that's bad! If I have to change to SQL at this stage, what do you suggest I do? Why was SQLite chosen for the book? Are there any marked advantages of using it?

**Comment by miguelgrinberg** [comment]
SQLite is a serverless database, it requires no installation. Other databases are more complicated to set up, but more powerful. So basically SQLite is good for prototyping because it is easy and lightweight. In any case, when you use SQLAlchemy you are abstracted from the database layer, so really switching to MySQL or Postgres should not give you a lot of trouble, other than learning how to set up the database server itself.

**Comment by priyankamandikal** [comment]
Are there any quick resources for this setup (SQL as well as Postgres)? And using them with Flask in particular?
