### ISSUE TITLE
'Large Application Structure'  question about from config import config

### ISSUE THREAD

**Issue by Leadh2o** [miguelgrinberg/flasky#154]
Hi, I'm learning flask by reading this book.
I have some questions about the unit 7 Large Application Structure.

For the code below, would anyone help me on these?

1) Can I use from . import config instead of from config import config?
2)the function 'app.config.from_object(config[config_name]),  config[config_name] is an object, but in these code, we haven't imported the Class in config, how can it work?

from flask import Flask, render_template
from flask.ext.bootstrap import Bootstrap
from flask.ext.mail import Mail
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(**name**)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
   # attach routes and custom error pages here
    return app

**Comment by miguelgrinberg** [comment]
> Can I use from . import config instead of from config import config?
No. The "." means import from the package, but at the root of the project there is no package.

> the function 'app.config.from_object(config[config_name]), config[config_name] is an object, but in these code, we haven't imported the Class in config, how can it work?
The `config` variable is a dictionary that references all the configuration classes by name. It is defined at the bottom of the config.py module.

**Comment by Leadh2o** [comment]
Thanks, it's clear now.

**Comment by lazarillo** [comment]
I am still confused by @Leadh2o 's first question.  I am also going through the book, but simultaneously trying to use it to help me along with a project I'm starting.

My question is this:  how does `from config import config` work?  Specifically, **how is the `config` module found?**  From the module in question, `app/__init__.py`, the module `config` is one level higher than the current module.  Moreover, there is no parent-level `__init__.py` file, so `config` is not even registered/recognized as part of the package.  So, how is `app/__init__.py` able to find it?  It seems to me that somehow the entire path that `flasky` lives at is being registered as either `$PATH` or `$PYTHONPATH`, so that it can be found, but I don't understand where this is happening.

In my particular case, where I am trying to follow along **and** create something similar in parallel, I have a `config` folder with - for the moment - a single `config.py` file.  So, I would have expected that I could call `from config.config import config`, but it isn't working.  When I move that `config.py` file up a level (and blow away the `config` folder), it still does not work (when calling `from config import config`).

How does the magic of finding the `config` module in the `flasky` app work?  Thanks!

PS  This is an ***AWESOME*** way to teach the holistic end-to-end web development!!!  The full app development **AND** the step-by-step git tags is really awesome!  Thanks so much, Miguel, for really "doing this right"!!!

**Comment by miguelgrinberg** [comment]
@lazarillo The `config` module is found because it is in the current directory. It does not matter from where it is imported, the fully qualified location for that module is just the module name. This is actually the same reason why you can say `from app import ...`. The `app` package is found because it is in the current directory, same as `config`. Hope this clarifies it.

**Comment by lazarillo** [comment]
Hi @miguelgrinberg Thanks for the quick reply!

Yes, I understand that is how it would normally work, but it is **not** in the current directory, I thought.

If I look at the `flasky` structure, I see, in part:

    app
        __init__.py
    .
    .
    .
    config.py

and it is the `app/__init__.py` file which contains the line that says `from config import config`.  So, as I understand it, the `config` module is **not** in fact in the current directory, but in the parent directory.  And I'm suspecting this is why my own example is not working, because it is trying to access a parent directory without an `__init__.py` package file.

Am I wrong?  Well, I know I'm wrong, but can you help me explain my mistake?  How is `config.py` **not** in the parent directory, with respect to `app/__init__.py`?

Thanks!
Mike

**Comment by miguelgrinberg** [comment]
You have a misunderstanding of what "current directory" means. The current directory is an operating system concept, each process has a directory that is marked as the current directory. By default, the current directory for a process is the directory from where the application was started (but the application itself can change this if it wants to).

In this case, you start the application from the flasky directory, right? So that is your current directory. From any Python modules you can import `config` and `app` without problem, because the current directory is in the Python import path.

**Comment by lazarillo** [comment]
Ahhh... yes, of course, thanks!  Since we've set up original file to be launched as simply `flasky.py` at that top directory level, all imports are relative to the location of `flasky.py`, and `config.py` is at that same level.

And regarding any "production resiliency" concerns, this should always "work out fine" because `flask run` will always look for the path under the `FLASK_APP` environment variable, which means that any daemon or whatever which calls `flask run` will always be experiencing the same "current directory".

Much appreciated!

**Comment by miguelgrinberg** [comment]
> And regarding any "production resiliency" concerns, this should always "work out fine" because flask run will always look for the path under the FLASK_APP environment variable, which means that any daemon or whatever which calls flask run will always be experiencing the same "current directory".

This is actually not a correct assessment, because in a production deployment you will not be using `flask run`, but a production-ready web server such as uWSGI or gunicorn. You will configure your application to run as a service, so there's going to be a systemd, supervisord, etc. definition file that tells your OS how to execute the application as a background service. In this configuration file you will specify what current directory to launch your application from.
