### ISSUE TITLE
Is Config.init_app() is empty and do nothing? Then why we have to call it in __init__.py?

### ISSUE THREAD

**Issue by reee** [miguelgrinberg/flasky#175]
I think the 
`app.config.from_object(config[config_name])`
will push the config to flask
so why we need this line:
`config[config_name].init_app(app)`

**Comment by reee** [comment]
I am not the only person:

https://www.v2ex.com/t/210678
(In Chinese)

**Comment by miguelgrinberg** [comment]
@reee the `init_app` method can be used to perform custom actions that apply to the configuration at initialization time. It is obviously optional, but note how in the production configuration I use it to set up emails to be sent to administrators when there is an error: https://github.com/miguelgrinberg/flasky/blob/master/config.py#L49

**Comment by shaoeChen** [comment]
SourceCode：
class ProductionConfig(Config):
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'data.sqlite')

    @classmethod
    def init_app(cls, app):
        Config.init_app(app) <----  my question here

        # email errors to the administrators
        import logging
        from logging.handlers import SMTPHandler
        credentials = None
        secure = None
        if getattr(cls, 'MAIL_USERNAME', None) is not None:
            credentials = (cls.MAIL_USERNAME, cls.MAIL_PASSWORD)
            if getattr(cls, 'MAIL_USE_TLS', None):
                secure = ()
        mail_handler = SMTPHandler(
            mailhost=(cls.MAIL_SERVER, cls.MAIL_PORT),
            fromaddr=cls.FLASKY_MAIL_SENDER,
            toaddrs=[cls.FLASKY_ADMIN],
            subject=cls.FLASKY_MAIL_SUBJECT_PREFIX + ' Application Error',
            credentials=credentials,
            secure=secure)
        mail_handler.setLevel(logging.ERROR)
        app.logger.addHandler(mail_handler)

Question：
  i try to understand your code but i think i am  stupid.
  in Class ProductionConfig you write『Config.init_app(app)』,it's still just『pass』right?
  『It is obviously optional』!
  but if i have write something there  it will run it follow my code!!
  ProductionConfig Inheritance Config and Override method init_app become classmethod but because 
  in Config init_app is staticmethod so i can call it again , right?
  the init_app is staticmethod
