### ISSUE TITLE
Database deadlocks using flasky in small "production" environment

### ISSUE THREAD

**Issue by stonemirror** [miguelgrinberg/flasky#180]
I've attempted to use flasky — and in particular, its `auth` module — as a basis for a small production system, with fewer than a dozen simultaneous users. In short order, I ran into an issue with deadlocks in the User table, apparently when attempting to update the "last seen" field. The result is a server error for the user and an entry along the lines of

```
Deadlock found when trying to get lock; try restarting transaction
```

in the Apache error log.

My first effort to address this was to go from using sqlite3 to MySQL which made no difference in the situation. I've been doing some searching around the web, but I have yet to find a really concrete example of how to address the need to roll back an attempted commit with SQLAlchemy.

As I understand it — and I don't think I understand it well — I need to do something along the lines of

```
try:
    db.commit()
except OperationalError:
    db.rollback()
    try:
        somehow_retry_the_commit_again_after_a_short_wait()
   except OperationalError()
        ....
```

or retry the commit() in a loop some (small) number of times, with a wait (increasing?) in between attempts.

Can you please give me any guidance on how to get this working as more than an "example app" in this context, Miguel? Thanks!

**Comment by miguelgrinberg** [comment]
The "deadlock found" error message is specific to MySQL. What error did you get with sqlite? Also, could you include the complete stack trace of the error?

**Comment by stonemirror** [comment]
It's definitely possible to get deadlocks with sqlite3, see [here](http://stackoverflow.com/questions/17348480/how-do-i-prevent-sqlite-database-locks) for example. Unfortunately, I don't have stack traces, this was running under WSGI on an Apache server, so all I had were the generic "server error" pages and the minimal information that Apache put into its own log.

I'm asking more as a general thing. Just as it's fine as a tutorial example to say (for instance)

```
url = 'http://google.com'
r = requests.get(url)
```

the correct way is to do something like

```
url = 'http://google.com'
try:
    r = requests.get(url)
except HTTPError:
   # do something to handle the error here
```

I'm looking for some general guidance on what to do when I get, say, an OperationalError on a commit(), which doesn't really depend on the engine, I don't think (or shouldn't, probably).

I do a rollback() in my `except` block, but _then_ what? Abandon the transaction? Retry it? How many times? With what sort of a wait time?

**Comment by miguelgrinberg** [comment]
@stonemirror I don't doubt it is possible to deadlock sqlite. I did not mean to imply you were incorrect, I was just asking for additional details about the sqlite problem, to help me have more information about the problem.

I now realize, you are really asking more about how to handle this type of error, and not about how to address this specific problem.

And unfortunately there is no single answer that fits all cases. It really depends. I'm really not a huge proponent of catching every possible error (I even gave [a talk](https://www.youtube.com/watch?v=8kTlzR4HhWo) about this topic). For example, what I would do in your requests example above is make a small addition to it, that in fact can cause more exceptions and not less:

```python
url = 'http://google.com'
r = requests.get(url)
r.raise_for_status()
```

In a Flask application where the requests call is expected to succeed, the above does the right thing (in my opinion. If everything succeeds, then there are no exceptions. If requests raises an exception, or if the HTTP request comes back with an error, the exceptions will bubble up and eventually Flask will get them. In development, the error will be presented in the Flask debugger, and in production the error will be logged, and a 500 code will be returned to the client. This is, in most cases, all you need to do.

In the case of SQLAlchemy errors I think the same idea applies. You expect all calls will succeed, so a failure needs to be handled as a 500 error in production, or a debugger trigger during development.

I think the deadlock problem is likely caused by a bug in your code. You should not accept that it is okay to get occasional deadlock errors, and instead you should figure out what that is happening. If you remove all the exception catching at least you will get the stack traces during development, and that can help figuring out where the problem is.

**Comment by stonemirror** [comment]
> I think the deadlock problem is likely caused by a bug in your code. You should not accept that it is okay to get occasional deadlock errors, and instead you should figure out what that is happening.

Well, here's the thing: it's just the `flasky` auth module code, I've made no changes to it at all (other than the experiment of changing the sqlite3 URI to a MySQL URI).

And there's nothing in there to handle errors at all, nor have I been able to find much by searching on the web, unfortunately. I want to reinstate the use of the login functionality in this app, but I'm going to run into the same issues, I'm sure, and I've got no real strategy for either diagnosing it or dealing with it. The best thing I can think of is to simply stop updating the "last seen" field at login. It's not as though there's all that much going on in there...

**Comment by miguelgrinberg** [comment]
> there's nothing in there to handle errors at all

No, that is incorrect. On a production deployment, any unexpected errors will be handled by logging the error and sending a code 500 response to the client. This is a serious error, if by "handling" you mean ignoring the error, that is not the proper solution in my opinion.

What I would like to suggest is that you remove all the exception catching code you've added, and then use the application in development mode until it crashes. That will give you a stack trace that could be helpful in determining what the problem is.

> The best thing I can think of is to simply stop updating the "last seen" field at login. It's not as though there's all that much going on in there...

Okay, so clearly you've done some debugging and determined that the last seen field is part of the problem. How do you trigger the deadlock situation? Do you have multiple clients logged in with the same user?

**Comment by stonemirror** [comment]
That's a possibility, and I could add some code I suppose to ensure that only one user can be logged in under a given ID at any particular time (although I think that would also represent an addition to the basic app framework; if that's a constraint, maybe it's worth mentioning or addressing in the code...)

Using the application "in development mode" — I'm thinking you mean via `python manage.py runserver` — with multiple users is a little dodgy: the users are on the other side of the continent, so I'm running the Flask app under Apache with mod_wsgi.

**Comment by miguelgrinberg** [comment]
Do you have a way to find out exactly how to trigger the deadlock situation? I want to understand how that happens, in particular if the bug ends up being on the book's code.

**Comment by stonemirror** [comment]
Unfortunately, not so far. What I do know is that it doesn't take very many users to cause it to happen, it seems that the update of the "last seen" field is a factor. The possibility that more than one person is using a single ID seems plausible.

What I _have_ gleaned from investigating this is that — at least in the case of a MySQL deadlock — retrying the transaction after a short delay is the Right Thing To Do. I've been thinking about some code that might look like this:

```
delay = INITIAL_DELAY
tries = 0
while tries < MAX_TRIES:
    try:
        db.session.commit()
    except OperationalError:
        db.session.rollback()
        sleep(delay)
        delay *= 2
        tries += 1
    else:
        break
if tries == MAX_TRIES:
#
# We failed to update the database...
#
```

Does that seem sound...?

**Comment by miguelgrinberg** [comment]
As a general solution for a non-web based application that might be acceptable, provided you also log the error (failing silently is a really bad idea, you need to record the occurrence of errors somewhere). On a web application I would not do this though. Depending on the values of `INITIAL_DELAY` and `MAX_TRIES` a request that repeatedly fails could hang one of your web server workers for several seconds, and that could be bad. In the worst case, an unrelated database problem could make all your web workers experience errors, and that will make all of them enter the retry loop and take a long time to finish each request, making your application completely unresponsive. If this is only writing the last seen value, my preference would be to try once and if it fails, just log the error and move on.

**Comment by stonemirror** [comment]
Okay, that makes some sense...
