### ISSUE TITLE
Reloading the value in os.environ

### ISSUE THREAD

**Issue by deveshaggrawal19** [miguelgrinberg/flasky#193]
I'm changing my environment dynamically using a script which changes the value of environment variable USD_INR using xml parsing. I added this script in crontab so that it changes the value for me automatically daily. But now after loading into python the os.environ.get('USD_INR') returns the same value. I saw the .bashrc file for my environment variables, the value is different but it not loading in python interpreter. How can i reload the values of os.environ automatically?

**Comment by miguelgrinberg** [comment]
Not sure if you are aware, each process has its own private environment, so saying that "a script changes the environment" does not really make much sense, since there isn't a central environment that you can change and have those changes be immediately available to currently running processes.

I think the best you can do is have your cron job update a file with the values of environment variables you want to update, and then have a background task in your server that periodically reads that file and changes the server's environment accordingly.

**Comment by deveshaggrawal19** [comment]
Actually, I did that only. But the problem is that the updated value is not read by the interpreter, after my interpreter session starts.

**Comment by deveshaggrawal19** [comment]
I have another question. You used the following syntax
db.event.listen(Comment.body, 'set', Comment.on_changed_body)
I couldn't understand it.

**Comment by miguelgrinberg** [comment]
> But the problem is that the updated value is not read by the interpreter, after my interpreter session starts.

That's correct. The process itself needs to read the updated value, for example from a file, and set it in its environment.

> I have another question. You used the following syntax
> db.event.listen(Comment.body, 'set', Comment.on_changed_body)
> I couldn't understand it.

That sets an event handler. When the body field of the Comment model is set, the on_changed_body function will be called. This is where I do the markdown rendering.

**Comment by deveshaggrawal19** [comment]
Thank you for clearing these questions.
