### ISSUE TITLE
Why your book is not in Apple's iBooks store?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [miguelgrinberg/flasky#239]
I would prefer to buy your book as an iBook from Apple's iBooks store to get future updates for free ;-)

More over an iBook can be interactive and also have all your videos included.

iBooks format is great for programing books compared to Kindle which's display is just to small for coding books - unfortunately.

Cheers
Tset

**Comment by Tset-Noitamotua** [comment]
Btw. will there be an update of the book? Last release is 2014 - a lot happened since then in web development.

**Comment by miguelgrinberg** [comment]
You need to talk to O'Reilly regarding distribution channels. I have zero control over that.

Regarding book updates, the book was written against Flask 0.10.1. The current version of Flask is 0.12, and there hasn't been a lot of changes since then. The project featured in the book can be used on version 0.12 without problem. There are a couple of things here and there that I would like to update, but that, once again, depends on O'Reilly, and I will be discussing this with them when the updates are ready.

Note that if you buy the ebook at the O'Reilly website, you also get free updates. Go to https://bit.ly/flaskbook for information.
