### ISSUE TITLE
Add Category to the Blog Post in the Form 

### ISSUE THREAD

**Issue by KevDi** [miguelgrinberg/flasky#249]
Hello, i would like to add Categories to the Posts. For that i have the following Many-To-Many Relationship added to the Post Model:
```python
class Post(db.Model):
   #...
   categories = db.relationship('Category',
                             secondary=has_category,
                             backref=db.backref('posts', lazy='dynamic'),
                             lazy='dynamic')

 class Category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, index=True)

has_category = db.Table('has_category',
                    db.Column('category_id', db.Integer, db.ForeignKey('category.id')),
                    db.Column('post_id', db.Integer, db.ForeignKey('post.id')))
```
Then i have changed the main/forms.py file and added a SelectField to the PostForm
```python
class PostForm(FlaskForm):
    body = PageDownField("What's on your mind?", validators=[Required()])
    category = SelectField('Category', coerce=int)
    submit = SubmitField('Submit')

    def __init__(self, user, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.category.choices = [(category.id, category.name)
                             for category in Category.query.order_by(category.name).all()]
```
The Categories are then displayed in the Select Field like it should.
Now I would like to give the User the option to add New Categories while creating a Blogpost. I have created a new view and a new html File to outsource the Post Creation from the Index.html. In that Html This template looks like the following:
```python
{% block page_content %}
    <div class="page-header">
        <h1>Add a new Post</h1>
    </div>
    <div class="col-md-4">
        <form action="#" method="post">
            {{ form.csrf_token }}
            {{ form.body.label }} {{ form.body }}
            {{ form.category.label }} {{ form.category}}
            <button>Add</button>
            <input type="submit" value="Go">
        </form>
    </div>
{% endblock %}
```
The Click on the Add Button should prompt the User for the name of the new Category, add it to the Database and update the Select Field to display the newly added Category.
But how can i archive this? Is there a solution without Javascript?
I hope this is the right Place to ask for help.

**Comment by miguelgrinberg** [comment]
> But how can i archive this? Is there a solution without Javascript?

I can think of three options, with only one being JavaScript first.

The first and possibly the best option, is to implement the category addition as an Ajax request. The browser will not need to reload the page, so the blog post form stays the same. So on the server you will have a new route to add a category, which you will invoke in JavaScript from the browser as a response to the click of the Add button.

Second option is to implement a separate form for adding a category. Then you can use standard form processing, without the need for JavaScript. The problem with this approach is that the contents of the blog post form will be erase as the browser switches pages, so for this option I would add some JavaScript that saves the contents of the form, so that they can be restored when the user returns to the blog post form.

The last option is to make the category field a test entry field, and remove the Add button. The blog post form on the server can look at the category, and add it automatically if it is not already in the database. This is the only option that is fully JavaScript free.

**Comment by KevDi** [comment]
Many thanks for your reply. I have solved it now with your first mentioned option but instead of the Add Button i have made the Category a normal StringField and get the Categories via an AJAX request. Then i use the JQuery Autocomplete Feature for the Textfield.

This is my Javascript Part:
```javascript
$(function () {
    $.post('/get-category').done(function (category) {
        $("#category").autocomplete({
            source: category['category']
        });
    })
});
```

The need view looks like this:
```python
@main.route('/get-category', methods=['GET', 'POST'])
@login_required
def get_category():
    return jsonify({
        'category': [category.name for category in Category.query.order_by(Category.name).all()]
    })
```

**Comment by miguelgrinberg** [comment]
Great. Glad you figured it out!
