### ISSUE TITLE
@auth.route('/unconfirmed')

### ISSUE THREAD

**Issue by yarps** [miguelgrinberg/flasky#262]
In:

```
@auth.route('/unconfirmed')
def unconfirmed():
    if current_user.is_anonymous or current_user.confirmed:
```

Do you see any difference/disadvantage or advantage in using:

```
@auth.route('/unconfirmed')
@login_required
def unconfirmed():
    if  current_user.confirmed:
```

**Comment by miguelgrinberg** [comment]
I don't see a big difference, but if an anonymous user navigates to `/unconfirmed`, they'll be sent to the login page instead of the index page, and after they login they'll be sent back to the unconfirmed page. It's not really a problem, but to me it seemed more consistent to bounce anybody that shouldn't see the unconfirmed page to the main page of the site, regardless of their login state.

**Comment by yarps** [comment]
Ok, thank you for the answer.
PS. Your book has still not be topped.
