### ISSUE TITLE
Get object from OpenStack

### ISSUE THREAD

**Issue by rolodub** [miguelgrinberg/flasky#274]
Hi,
I have 2 questions:

I'm developing my site/service with your fantastic book support.
I'm storing objects on openstack and I access them with python swiftclient.
1) I don't understand where I must instantiate a connection class (credentials are stored in os environnement variables)
- Connect on time in app.__init__?
or
- Connect every time I need in views?

2) Is there a way to read a binary file stored on open stack directly. For the moment, I first copy it on the server...
`r = requests.get(aaf_link)`
`filename = os.path.join(UPLOAD_FOLDER, 'aaffile.aaf')`
`with open(filename,'wb') as f:`
`    f.write(r.content)`
`aaf = AafReader(filename)`

Thanks

**Comment by miguelgrinberg** [comment]
> Connect on time in `app.__init__`?
> or
> Connect every time I need in views?

This really depends on how you have structured your server application. If your app is not multithreaded for example, you can create a single connection that is global to your process. If you handle requests in multiple threads, then that's not going to work, and instead you need to use a new connection in each thread, so your second option makes more sense, and what makes even more sense is to use some sort of connection pool (maybe using a queue), so that you are not creating  lots of new connections.

> Is there a way to read a binary file stored on open stack directly

That largely depends on your `AafReader` class. Did you build that yourself? If you did, then change it so that instead of taking a filename it takes a stream. Then you can send a `BytesIO` stream initialized from your `r.content` data.

**Comment by rolodub** [comment]
1) Thank you, you showed me the good way with the connection pool: back to the docs and found swift client.service which is "A higher-level API aimed at allowing developers an easy way to perform multiple operations asynchronously using a configurable thread pool". [https://docs.openstack.org/developer/python-swiftclient/service-api.html#keystone-v2](url)
Powerful!

2) As I principally use [https://github.com/markreidvfx/pyaaf/blob/master/aaf/storage/File.pyx](url) which is file reading based in my AafReader... It seems I must first download the file before reading?

**Comment by miguelgrinberg** [comment]
If you don't have control over the code of the AafReader class and it can only take a filename as input, then it seems you will have to write the data to a file. But it should be easy to add support for a stream, if you want to spend some time on somebody else's code.

**Comment by rolodub** [comment]
Indeed, but I'm afraid it would be difficult because the pyaaf lib is a Python Bindings for the Advanced Authoring Format (AAF) written in Cython.
As I'm a python beginner thinking about Cython makes me affraid...
Furthermore, I think that the C lib [http://aaf.sourceforge.net/docs/aafapiman/interfaceIAAFFile.html#details](url) is file based...
Thet say:"Any filesystem file can be opened for reading by multiple IAAFFile-supporting objects."

**Comment by miguelgrinberg** [comment]
@rolodub Another thing you can do is hide the writing to a temp file in a function, so that you don't have to maintain that in your code. Your wrapper function takes a Python stream, creates a temp file, writes the stream to it, invokes the aaf reader and then when you are done deletes the file.

**Comment by rolodub** [comment]
Good idea, that's what I'm going to do. Thank you!
