### ISSUE TITLE
self.follow(self) causes unittest error

### ISSUE THREAD

**Issue by AdamWangDoggie** [miguelgrinberg/flasky#279]
HI miguel,sorry to bother.
It's about a func in User.__init__ to make users follow themselves,the codes in your book was like below,
`self.follow(self)`

but in your repository:
`self.followed.append(Follow(followed=self))`

And that in your book causes unittest error:
`sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <User at 0x7fb90d3e49b0> is not bound to a Session, and no contextual session is established; lazy load operation of attribute 'followed' cannot proceed`

I don't understand what caused the error, how it affects the result of unittest, and what's the differences between the two above.

Hope u can reply this, thx

**Comment by miguelgrinberg** [comment]
Do you have the complete stack trace of the error please?

**Comment by miguelgrinberg** [comment]
Great. So you can see in the stack trace that the error occurs when you do `self.followed.filter_by(...)` in line 232 of models.py. This line instructs the database to do a join operation between two tables, to find if the user you want to follow was already added. The problem is that `self` isn't in the database yet, so it does not have an `id` assigned, which makes the join operation impossible.

The way I implemented that initial self follow is by just doing `self.folllowed.append()` which does not require any database joins or searches.

You could probably make `self.follow(self)` work in the constructor if you add a check to skip the `is_following()` check when the instance does not have an `id` still.

**Comment by AdamWangDoggie** [comment]
OK, I got it. I should concentrate more. 
Thank u very much, and I'll close the issue.

By the way, in styles.css ,I think the 'post-content' should be replaced by 'post-body', and the 'post-author' should have a 'margin-left:48px'. Both in ur repository.
