### ISSUE TITLE
Import statement inside function

### ISSUE THREAD

**Issue by greyli** [miguelgrinberg/flasky#281]
Hi, Miguel. As PEP8 said,

>  Imports are always put at the top of the file, just after any module comments and doc strings, and before module globals and constants.  

However, there are many import statements were inside the function, such as [here](https://github.com/miguelgrinberg/flasky/blob/master/manage.py#L68). Is it better to move them to the top of the file? 
Besides, the import statement below was redundant with [this](https://github.com/miguelgrinberg/flasky/blob/master/manage.py#L17). Can it be removed?

**Comment by miguelgrinberg** [comment]
Yes, those redundant imports should be removed, good catch.

Using imports inside functions is sometimes justified, in my opinion. Consider [this example](https://github.com/miguelgrinberg/flasky/blob/master/manage.py#L58). If I move the profiler's import to the top, then it will be imported for every use of the application, even though there is only one specific use case that requires the profiler. The application will be bigger because of this import than in most cases isn't needed.

However, I think the example you indicated does not really need the imports to be inside the function, for those you don't really gain much by keeping them inside, and obviously I missed that the models eventually were added at the top as well, so they are now duplicated. I will remove those imports from the function.

**Comment by greyli** [comment]
Thanks for the detail explanation.
