### ISSUE TITLE
how to register or add the admin account?

### ISSUE THREAD

**Issue by IvyGongoogle** [miguelgrinberg/flasky#284]
hello, like your book, but how to register or add the administrator account?
can you give some advises?

**Comment by miguelgrinberg** [comment]
You need to set the environment variable `FLASKY_ADMIN` to the email address of the administrator. When a user with that email signs up, they will be assigned the admin role.

**Comment by AdamWangDoggie** [comment]
In addition:
Notice miguel said 'When a user with that email signs up', that means u can only register an new account as administrator.
Because the operations setting role for a user were defined in User.__init__().
U can't set an existed user account to administrator, unless u change through  sqlite database immidiately.

**Comment by IvyGongoogle** [comment]
@miguelgrinberg @AdamWangDoggie sorry to reply later. thanks million.
