### ISSUE TITLE
how to change primary key column

### ISSUE THREAD

**Issue by ilumer** [miguelgrinberg/flasky#341]
I have a  problem,. I want to change the primary key column.
```
old user 
followed = db.relationship('Follow', foreign_keys=[Follow.follower_id], 
                               backref=db.backref('follower', lazy='joined'), 
                               lazy='dynamic', cascade='all, delete-orphan') 
followers = db.relationship('Follow', foreign_keys=[Follow.followed_id], 
                                backref=db.backref('followed', lazy='joined'), 
                                lazy='dynamic', cascade='all, delete-orphan')
old follow
follower_id = db.Column(db.Integer, db.ForeignKey('Users.id'), primary_key=True) 
followed_id = db.Column(db.Integer, db.ForeignKey('Users.id'), primary_key=True) 
```
```
user
following = db.relationship('Follow', foreign_keys=[Follow.follower_id],
                                backref=db.backref('followers', lazy='joined'),
                                lazy='dynamic', cascade='all, delete-orphan')
followers = db.relationship('Follow', foreign_keys=[Follow.following_id],
                                backref=db.backref('following', lazy='joined'),
                                lazy='dynamic', cascade='all, delete-orphan')
follow
follower_id = db.Column(db.Integer, db.ForeignKey('Users.id'), primary_key=True)
following_id = db.Column(db.Integer, db.ForeignKey('Users.id'), primary_key=True)
```
the sqlite3 output `(sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL [SQL: 'ALTER TABLE follows ADD COLUMN following_id INTEGER NOT NULL']`.
The `following_id` is primary_key and can not be set null.Can you give some ways that can try to solve this problems. I am sorry for my English.

**Comment by miguelgrinberg** [comment]
Alembic is not going to detect that you are renaming a column, and instead will try to delete the old column and add a new one. The new column fails to be inserted because it is a primary key, so it needs to have a unique value for each row, but all the existing rows in the table are going to get a NULL value inserted.

You are going to need to do something custom to get this migration script to work. For example, you can load all the rows from the table into memory, then clear the table, then rename the column, and finally add back all those rows.
