### ISSUE TITLE
Question about current_user._get_current_object()

### ISSUE THREAD

**Issue by shaoeChen** [miguelgrinberg/flasky#348]
I try to understand Flask Web example 11-3 app/main/views.py
```python
post=Post(body=form.body.data,
          author=current_user._get_current_object())
```
but I was thinking about something, why don't use current_user.id?
i try to create a View Function
```python
@blog.route('/blog_post/c', methods=['GET', 'POST'])
@login_required
def post_blog_post():
    form = Form_Blog_Post()
    if form.validate_on_submit():
        print(current_user.id)
        print(current_user._get_current_object())
        print(current_user._get_current_object().id)
```
I got the following result
```shell
1
username:username, email:email@email.com
1
```
current_user implement through LocalProxy, while user login , then set the _request_ctx_stack.top.user= login user, i don't understand why we need use current_user._get_current_object() to got the user object.
```python
    _request_ctx_stack.top.user = user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
    return True
```
i always thought current_app._get_current_object or current_user._current_object is used to the request not in the same context, like the example『sendmail.py』, it seem i am wrong.
i am sorry , my english is very poor, hope you can understand what i mean!

**Comment by miguelgrinberg** [comment]
You have two options. One is what I did:

    post=Post(body=form.body.data,
              author=current_user._get_current_object())

the other is to use the user `id`:

post=Post(body=form.body.data,
          user_id=current_user.id)

Both are equivalent, but I prefer the former because it uses objects instead of IDs. The reason why you need to add `_get_current_object()` is that as you stated, `current_user` is not a `User` object, it is a proxy object. SQLAlchemy gets confused if you give it the proxy, so you have to retrieve the actual `User` object from inside the proxy.

**Comment by shaoeChen** [comment]
Yes, I see. 
Thanks for your direction.
