### ISSUE TITLE
Default config and test command

### ISSUE THREAD

**Issue by latusaki** [miguelgrinberg/flasky#36]
With the setup flasky is using, the default config is applied and an application is created using it, before another app is created using the testing config. What ways are there to avoid this? I am looking to either  delete everything that has happened before create_app in unit tests, or change the initialization process. A simple solution would be to move the     `app = create_app(os.getenv('FLASK_CONFIG') or 'default')
    manager = Manager(app) ` code inside a manager command, but that is not possible..

**Comment by miguelgrinberg** [comment]
The default app is used for a couple of things: (1) to enable the `test` command to be launched from `manage.py`; and (2) to enable the calls to `url_for()` within tests to work.

You can address (1) by running the tests from a separate script:

    import unittest
    tests = unittest.TestLoader().discover('tests')
    unittest.TextTestRunner(verbosity=2).run(tests)

Unfortunately (2) is a bit harder to address, because `url_for()` normally wants a request context. I haven't tried this, but probably setting `SERVER_NAME` to some hostname in the testing configuration will allow `url_for()` to run. I'm not sure if the resulting URLs will work with the test client though, maybe a fix is needed there as well, since the test client expects relative URLs without hostname.

**Comment by miguelgrinberg** [comment]
Actually, regarding (2) above, I think you can easily emulate what Flask-Script does, which is to run commands under a test request context. A test context can be created in the `setUp()` methods of the test cases.

**Comment by latusaki** [comment]
Thank you for the pointers, I will investigate these options. Before closing, I feel I should say that your book is amazing, great piece of work!

**Comment by v-ken** [comment]
Related to this issue, I was wondering if there was a way to use a different database URI for the unit test? Because an app is created (which initialises the db) using the 'default' config in the manage.py script, I am experiencing some difficulties changing the database URI when another app is created in the unit test `self.app = create_app('testing')`.

**Comment by latusaki** [comment]
@v-ken  my solution to the default config problem was providing the system variable when I wanted a different config. So when I run tests, I set FLASK_CONFIG = testing on my system.

**Comment by v-ken** [comment]
Thanks. That's definitely a solution. Was wondering if there was a way to reset the sqlalchemy DB to use the new URI? Seems like a much cleaner implementation as we can fully rely on `self.app = create_app('testing')` in the unit test.

**Comment by miguelgrinberg** [comment]
@v-ken The app that is created as part of setting up Flask-Script is not related to the app that is created for the tests, so I'm not sure why the interfere with each other. Have you debugged your issue to understand what is exactly the problem?

**Comment by v-ken** [comment]
@miguelgrinberg Thanks for your response. That's what I thought as well. But I think both apps might be referencing a single `db = SQLAlchemy()` instance. And I'm not sure if this is the reason but according to the [Flask-SQLAlchemy docs](https://pythonhosted.org/Flask-SQLAlchemy/config.html):
>Note that some of those cannot be modified after the engine was created so make sure to configure as early as possible and to not modify them at runtime.

I tested by cloning this repo and setting the following in the `.env` file:

    FLASK_CONFIG=development
    TEST_DATABASE_URL=mysql://username:password@localhost/db_test
    DEV_DATABASE_URL=mysql://username:password@localhost/db

**Comment by miguelgrinberg** [comment]
What happened when you tested the `.env` file above? Did you get any error?

**Comment by v-ken** [comment]
I did get some errors when I ran the unit test but the point was that I noticed all the DB operations were performed on the `DEV_DATABASE_URL` instead of `TEST_DATABASE_URL`.
Correct me if I'm wrong but even though `FLASK_CONFIG` is set to development, I would've thought that the app created in the unit test should use the 'testing' config?

**Comment by v-ken** [comment]
@miguelgrinberg Can you confirm that this issue isn't happening on your end? Just want to make sure that it isn't a mistake on my side.

**Comment by v-ken** [comment]
Hi @miguelgrinberg , did you get the time to confirm if this is an issue on your end as well? Can I open this as a new issue?

**Comment by miguelgrinberg** [comment]
Sorry I did not answer, @v-ken. This does not happen here, when I run the tests a `data-test.sqlite` file is created, and my debug database is unaffected. Are you using a pristine copy of the project or do you have changes?

**Comment by ithinco** [comment]
I got the same problem as @v-ken met, after add the test case of "test_roles_and_permissions" and "test_anonymous_user", I got the error:

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: users.email [SQL: u'INSERT INTO users (email, username, role_id, password_hash) VALUES (?, ?, ?, ?)'] [parameters: ('john@example.com', None, 3, 'pbkdf2:sha1:1000$R377YAwK$7ac350e7f748f8591774be665bd1dd1ce5d5bf79')]

and the data-test.sqlite is created but empty. I ran migrate and upgrade command but didn't work.
