### ISSUE TITLE
heroku local:run flask deploy not upgrading database on heroku

### ISSUE THREAD

**Issue by ravibilla** [miguelgrinberg/flasky#377]
I am having trouble runnign this command
`heroku local:run flask deploy`

I get the following output
`INFO  [alembic.runtime.migration] Context impl SQLiteImpl.`
`INFO  [alembic.runtime.migration] Will assume non-transactional DDL.`

Iam not seeing the expect output below as mentioned in the book
`[OKAY] Loaded ENV .env File as KEY = VALUE Format INFO Context impl SQLiteImpl. INFO Will assume non-transactional DDL. INFO Running upgrade -> 38c4e85512a9, initial migration INFO Running upgrade 38c4e85512a9 -> 456a945560f6, login support INFO Running upgrade 456a945560f6 -> 190163627111, account confirmation INFO Running upgrade 190163627111 -> 56ed7d33de8d, user roles INFO Running upgrade 56ed7d33de8d -> d66f086b258, user information INFO Running upgrade d66f086b258 -> 198b0eebcf9, caching of avatar hashes INFO Running upgrade 198b0eebcf9 -> 1b966e7f4b9e, post model INFO Running upgrade 1b966e7f4b9e -> 288cd3dc5a8, rich text posts INFO Running upgrade 288cd3dc5a8 -> 2356a38169ea, followers INFO Running upgrade 2356a38169ea -> 51f5ccfba190, comments
 `
What am i doing wrong ?

**Comment by miguelgrinberg** [comment]
Did you do a `git push` to heroku so that the new code is installed? Maybe you are running deploy on the previous version of the application?

**Comment by vital1312** [comment]
I have the exactly same problem. Doing all steps as in your book, but I get only this:

heroku local:run flask deploy
(venv) C:\Users\vital\Documents\CS50 Web\flasky000>heroku local:run flask deploy
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
(venv) C:\Users\vital\Documents\CS50 Web\flasky000>

set aside git push to heroku,  couse I want to run app locally. 
btw, I git pushed on heroku, too, and Im getting internal error there

**Comment by miguelgrinberg** [comment]
@vital1312 try these two commands and show me the output:

    heroku local:run flask db history
    heroku local:run flask db current

**Comment by vital1312** [comment]
**heroku local:run flask db history**
51f5ccfba190 -> b68b40e2c6f9 (head), deploy problemc 17
2356a38169ea -> 51f5ccfba190, comments
288cd3dc5a8 -> 2356a38169ea, followers
1b966e7f4b9e -> 288cd3dc5a8, rich text posts
198b0eebcf9 -> 1b966e7f4b9e, post model
d66f086b258 -> 198b0eebcf9, caching of avatar hashes
56ed7d33de8d -> d66f086b258, user information
190163627111 -> 56ed7d33de8d, user roles
456a945560f6 -> 190163627111, account confirmation
38c4e85512a9 -> 456a945560f6, login support
< base> -> 38c4e85512a9, initial migration

____
**heroku local:run flask db current**
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
b68b40e2c6f9 (head)

**Comment by miguelgrinberg** [comment]
That's actually what I expected. Your last migration in the history is `b68b40e2c6f9`. Your database is currently at that migration. So when you run an upgrade there is nothing to do. So I believe there is no problem.

**Comment by vital1312** [comment]
Thank you for your assistance and your time.  the problem is that I still cannot run it locally on heroku.  (remark: I work in WIn 10, so my Procfile contains: web: waitress-serve --port=$PORT flasky:app).
 I've made  **heroku local:run flask deploy**, - all went well,  but **heroku local**
returns  such errors:  

(venv) C:\Users\vital\Documents\CS50 Web\flasky0>heroku local
[OKAY] Loaded ENV .env File as KEY=VALUE Format
20:24:05 web.1   |  Traceback (most recent call last):
20:24:05 web.1   |    File "C:\Users\vital\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_m
ain
20:24:05 web.1   |      "__main__", mod_spec)
20:24:05 web.1   |    File "C:\Users\vital\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
20:24:05 web.1   |      exec(code, run_globals)
20:24:05 web.1   |    File "C:\Users\vital\Documents\CS50 Web\flasky0\venv\Scripts\waitress-serve.exe\__main__.py", line 9, in <m
odule>
20:24:05 web.1   |    File "c:\users\vital\documents\cs50 web\flasky0\venv\lib\site-packages\waitress\runner.py", line 274, in ru
n
20:24:05 web.1   |      _serve(app, **kw)
20:24:05 web.1   |    File "c:\users\vital\documents\cs50 web\flasky0\venv\lib\site-packages\waitress\__init__.py", line 11, in s
erve
20:24:05 web.1   |      server = _server(app, **kw)
20:24:05 web.1   |    File "c:\users\vital\documents\cs50 web\flasky0\venv\lib\site-packages\waitress\server.py", line 51, in cre
ate_server
20:24:05 web.1   |      adj = Adjustments(**kw)
20:24:05 web.1   |    File "c:\users\vital\documents\cs50 web\flasky0\venv\lib\site-packages\waitress\adjustments.py", line 224,
in __init__
20:24:05 web.1   |      setattr(self, k, self._param_map[k](v))
20:24:05 web.1   |  ValueError: invalid literal for int() with base 10: '$PORT'
[DONE] Killing all processes with signal  SIGINT
20:24:05 web.1   Exited with exit code null


I just cannot get the problem .  When in the terminal I put  commands  **waitress-serve --port 8000 flasky:app** and **flask run** , they work perfectly. Could you advise something? Thank you!

**Comment by miguelgrinberg** [comment]
The usage `$PORT` is a Unix thing, that does not work on Windows. I believe on Windows you have to use `%PORT%`

**Comment by vital1312** [comment]
Thank you very much. It really helped to deploy locally, but there is some issue with the command **heroku local** :
(venv) C:\Users\vital\Documents\CS50 Web\flasky0>heroku local
[OKAY] Loaded ENV .env File as KEY=VALUE Format
_(nothing is happening further, just the cursor blinking. So I am forced to interrupt)_
[WARN] Interrupted by User
^C Quit executing of the batch file[Y(yes)/N(no)]? y

**Comment by miguelgrinberg** [comment]
Did you try entering a port number hardcoded in the procfile? Maybe the `%PORT%` is also not working?

**Comment by vital1312** [comment]
I've amended Procfile, tried at first this: 
web: waitress-serve --port=5000 flasky:app
and then tried:
web: waitress-serve --port=8000 flasky:app

And both times with the same empty result.
I found this issue was described before by another person here: https://github.com/miguelgrinberg/flasky/issues/436
But there was solution, too. As I can see

**Comment by miguelgrinberg** [comment]
@vital1312 does the server respond to requests when it gets into the cursor blinking with no other output?

**Comment by vital1312** [comment]
It appears that server actually is working when the cursor blinking with no other output! Thank you!
Even with the --port=%PORT% in Procfile ( --port=5000 works,too).
I loaded http://hp-major:5000/ and the flasky app was there, with the empty database (is it normal?), but working fine. I even added a couple of users. So, I guess, the problem is solved. An empty output is not a big deal, I guess. I work in PyCharm (up-to-date version), maybe it's related somehow?

**Comment by miguelgrinberg** [comment]
@vital1312 according to [this page](https://docs.pylonsproject.org/projects/waitress/en/stable/logging.html) you have to add a middleware from another package to add request logging, so yes, I think you have it all working and the server just does not log requests. It should log exceptions though.
