### ISSUE TITLE
question: flasky around existing database

### ISSUE THREAD

**Issue by caverac** [miguelgrinberg/flasky#380]
I've been following Flask Web Development to create a flask app around an existing database. My problem is when I get to the point where I need to define the classes in `models.py`. Followed [this](https://stackoverflow.com/questions/17652937/how-to-build-a-flask-application-around-an-already-existing-database) solution, just cannot make it work

1. If I try

```
class User(db.Model):        
    __table__ = db.Model.metadata.tables['users']
```

I get a `KeyError` exception

2. If I try `base.metadata.reflect(db.engine)` right before defining the `Users` class, I get an error telling me that I need a context, so if I do

```
from . import create_app
app = create_app('default')
```

in `models.py` then I get an import execption.

Any suggestions? Thanks in advance!

**Comment by miguelgrinberg** [comment]
Sorry, it appears this issue fell through the cracks and I never responded. You can't really create your models by hand when you are asking SQLAlchemy to reflect an existing database. You may want to look at the [automap](https://docs.sqlalchemy.org/en/latest/orm/extensions/automap.html) extension, which reflects the database and also automatically creates models for the ORM.

I'm going to close the issue since it's been so long. If you need more assistance please reopen or start a new one.

**Comment by zonedoutfella** [comment]
For anyone facing this issue, the `KeyError` occurs because the `models.py` is executed before the `reflect()` call, so the tables aren't reflected yet. This [stackoverflow answer](https://stackoverflow.com/a/72691285) shows how to resolve it.
