### ISSUE TITLE
'User' has no attribute 'roles'

### ISSUE THREAD

**Issue by dotRollen** [miguelgrinberg/flasky#383]
Hello Miguel, wanted to thank you for the amazing book! I'm converting the app to a MonogEngine app instead of SQLAlchemy and I realized that for User there is this code

```
    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['FLASKY_ADMIN']:
                self.role = Role.query.filter_by(name='Administrator').first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()
        if self.email is not None and self.avatar_hash is None:
            self.avatar_hash = self.gravatar_hash()
self.follow(self)
```

I get the error `'User' object has no attribute 'role'` if I change it to role_id it's fine and works as intended but with just role I get an error. Can't tell if this is a type or the way it works is changed by me using db.Document inheritance from MongoEngine... Doesn't make sense though if that was the case, do you mind helping me out?

**Comment by miguelgrinberg** [comment]
The `role` attribute is somewhat magical, as it is added by SQLAlchemy to represent the relationship between uses and roles. You can see it defined [in this line](https://github.com/miguelgrinberg/flasky/blob/master/app/models.py#L27), in the backref section.

You can implement the same logic with `role_id`, but `role` is nicer, as it allows you to work with Python object instead of numeric ids from the database.

**Comment by dotRollen** [comment]
OH WOW!! I can't believe I missed that! That just made me grow my respects for SQLAlchemy even more. I'm gonna have to get really creative to do a similar solution with MongoEngine. I definitely like that a lot more than doing a query on objectids and adding work load to the DB. 

I'll see if I can find a solution and post it here! Thank you again Miguel!!! You're a big inspiration to this fellow latino :) !
