### ISSUE TITLE
flasky-7a, i run app/email.py report an error: ImportError: cannot import name 'current_app'

### ISSUE THREAD

**Issue by lvorcool** [miguelgrinberg/flasky#388]
![image](https://user-images.githubusercontent.com/21286480/47137600-9d1df800-d2e9-11e8-91a6-4068e401d520.png)

**Comment by miguelgrinberg** [comment]
Do you have any files named `flask.py` by any chance?

**Comment by lvorcool** [comment]
no,No, I wrote the code in the imitation book. I only saw the file named `flasky.py`.
![image](https://user-images.githubusercontent.com/21286480/47195258-b37d8f80-d38d-11e8-9f72-6c12adc54b43.png)

**Comment by miguelgrinberg** [comment]
Sorry, didn't realize you were running another file. Why do you need to run `app/email.py` on its own? It's not a runnable file. The problem is that this file is called `email.py` and it shadows an `email` module in the Python standard library. It isn't a problem when the directory where `email.py` is is not in the path, which is the normal way the application is executed. It is a problem if you run `email.py` as a main file, because then the Python path will include that directory.

**Comment by lvorcool** [comment]
The initial problem was that I wrote the database model, but I connected the mysql database. I executed the `app/models.py` file and the error was reported. 
![image](https://user-images.githubusercontent.com/21286480/47211127-4edf2680-d3c7-11e8-9dca-9f8558a7c769.png)

So I executed the email.py file to see where the problem is.The error message is the same

**Comment by miguelgrinberg** [comment]
Well, I told you above what the problem is. Rename `email.py` to some other name and the problem will be resolved.

**Comment by lvorcool** [comment]
No more abnormal errors are reported, but what is the cause of the problem?

**Comment by miguelgrinberg** [comment]
Take a look at the stack trace to see where the problem is. The `Flask` class is imported, this in turn imports some things from Werkzeug, which in turn tries to import something from `email.utils`. Because there is an `email.py` in the path, that is given preference over the `email` package in the Python standard library. When `email.py` is imported a circular import occurs, as this file tries to import items from flask, which are in the same location as the `Flask` class, which is currently being parsed but not completely parsed yet.

**Comment by lvorcool** [comment]
@miguelgrinberg 
Thank you, now the US time is five or six in the morning, you get up early, I admire.

**Comment by miguelgrinberg** [comment]
@lvorcool Oh, no, I'm currently in Ireland. :)
