### ISSUE TITLE
can use Apache+mod_wsgi deploy project？

### ISSUE THREAD

**Issue by waliguder** [miguelgrinberg/flasky#396]

**Comment by waliguder** [comment]
And how to use 0.0.0.0 start  the flask??

**Comment by miguelgrinberg** [comment]
You can use any WSGI compatible Python web server. I normally do not recommend people Apache+mod_wsgi because that has some limitations for certain types of web applications, but for this particular application it should work.

If you want to run the development web server on 0.0.0.0 you can use `flask run -h 0.0.0.0`.
