### ISSUE TITLE
Database trigger not added in test environment

### ISSUE THREAD

**Issue by okomarov** [miguelgrinberg/flasky#412]
Apologies if this does not belong here but any pointer would be highly appreciated!

I have a migration with this manually created trigger:
```python
SQL_statement = """
        CREATE OR REPLACE FUNCTION log_name_changes() RETURNS trigger AS
        $BODY$
        BEGIN
          INSERT INTO name_history (name, retrieved_on)
          VALUES(NEW.name, NEW.retrieved_on);

          RETURN NEW;
        END;
        $BODY$

        LANGUAGE plpgsql VOLATILE
        COST 100;"""
    op.execute(SQL_statement)

    SQL_statement = """
        CREATE TRIGGER name_changes
          AFTER UPDATE or INSERT ON name_history
          FOR EACH ROW EXECUTE PROCEDURE log_name_changes();"""
    op.execute(SQL_statement)
```
The trigger is correctly created after a `flask db upgrade` but is NOT created on the **test database**:

My setup and teardown functions for the testing environment are:

```python
class AppTestCase(unittest.TestCase):
    def setUp(self):
        self.app = Flask(__name__)
        self.app.config.from_object(config_to_use)

        db.init_app(self.app)

        self.app_context = self.app.app_context()
        self.app_context.push()

        db.drop_all()
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

        self.app_context.pop()
```

Do I need to define listeners for the specified `name_history` table for `db.create_all()` to pick up the trigger creation?

**Comment by miguelgrinberg** [comment]
The `db.create_all()` function is not part of Flask-Migrate or Alembic, it knows nothing about your migrations, so it just creates the tables associated with the models. You have two options:

1. move the trigger creation to a common place that you can call from the migration and from your unit test `setUp()` method.
2. change your `setUp()` method in the unit tests to create the database through the migrations instead of with `db.create_all()`.

**Comment by okomarov** [comment]
@miguelgrinberg Thanks for the quick reply!
