### ISSUE TITLE
Can't deploy Tensorflow chatbot on a Apache web server using Flask 

### ISSUE THREAD

**Issue by JulianaThayil** [miguelgrinberg/flasky#445]
Im trying to deploy my flask chatbot on Wamp server using mod_wsgi. I am able to run a simple flask app on wamp. But when i try to run my flask AI chatbot that uses python packages such as tensorflow, numpy, tflearn etc, wamp wouldn't load it. I tested the flask app locally without any problem. But it doesn't work on wamp apache. Also it is unable to load the json file.

This is how i have configured apache

LoadFile "c:/users/juliana thayil/appdata/local/programs/python/python36/python36.dll"
LoadModule wsgi_module "c:/users/juliana thayil/appdata/local/programs/python/python36/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/users/juliana thayil/appdata/local/programs/python/python36"
WSGIPythonPath "C:/wamp64/www/miniproject"

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot c:/wamp64/www
    WSGIScriptAlias /miniproject c:/wamp64/www/miniproject/web.wsgi
    <Directory c:/wamp64/www/miniproject>
         require all granted
    </Directory>
</VirtualHost>

**Comment by miguelgrinberg** [comment]
Did you see any interesting errors or messages in the log? What do you mean by "it is unable by load the json file"? What json file is this?

**Comment by JulianaThayil** [comment]
There are no errors in the log but i think apache is not able to access the python packages installed in the main python installation. 
The json file contains the dataset that the chatbot uses to produce responses.  

Do i have to create a virtual environment for the flask app and install all the packages in it? If so, what changes should i make to the apache configuration file ?

**Comment by miguelgrinberg** [comment]
@JulianaThayil You may be looking at the wrong log file then, because if Python cannot load packages, then there should be an import error message in the log. This is the Apache error log that you are checking, correct? See https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html for details.

You definitely need to install all your dependencies. Whether you do it on a virtualenv or in the global interpreter is a matter of preference. I would make a virtualenv to keep things neatly organized. Unfortunately I don't use Apache/mod_wsgi, so cannot tell you what to change.

I suggest you first concentrate on having good logs for errors, because without that is like driving with a blindfold. You will not be able to figure out the fix if you don't know what the problem is.

**Comment by JulianaThayil** [comment]
I am able to debug after adding `LogLevel debug`  to the configuration. 
Thank you so much for your help.
