### ISSUE TITLE
current_user vs current_user._get_current_object()

### ISSUE THREAD

**Issue by rubenflamshepherd** [miguelgrinberg/flasky#480]
Hey Miguel! Really enjoyed your book!

Just wanted some clarification. This line [here](https://github.com/miguelgrinberg/flasky/blob/6ff384af1525d536a97376242cb2701638ef25b6/app/auth/views.py#L100), should that instead read

 ```
db.session.add(current_user._get_current_object())
```

You mention on pg. 152 of the 2nd Edition the need to unwrap context variables. I haven't tested the actual code but I surmise that this would throw an error if someone actually tried to reset their password?

**Comment by miguelgrinberg** [comment]
I would need to test this to make sure, in many cases the proxy object can be used and everything works well. In any case, I just realize this `db.session.add()` call can be removed completely and things will still work, because the user is already in the session from when the user loader function queried it.
