### ISSUE TITLE
Flasky flash message problem

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#51]
To replicate the problem in Flasky:

Enter wrong login credentials, message "Invalid username or password." should appear.
On browser, press "back" and "forward", same message should be there.

Any idea on how to fix this? Thanks!

**Comment by miguelgrinberg** [comment]
This is a side effect of how message flashing works. The idea is that the message is shown right after the situation that cause the error happened, but then the error message is suppressed. Same thing happens if you hit refresh on a page that has a flashed message, the message is expected to go away in that case too.

**Comment by harrywang** [comment]
@miguelgrinberg thanks a lot for the answer.
