### ISSUE TITLE
Something can't understand in page 80

### ISSUE THREAD

**Issue by testerman77** [miguelgrinberg/flasky#63]
Hi Miguel,
Thanks you for your book,
There're some sentences I can't understand in the book.

In the second paragraph of the page 80,<b>"Importing these modules causes the routes and error handlers to be associated with the blueprint."</b>

Doesn't the routes and error handlers associated with the blueprint by the decorate,like the @main.route and @main.app_errorhandler?

sorry for the pool english;-)

**Comment by miguelgrinberg** [comment]
@testerman77 the module(s) that have routes and error handlers need to be imported for them to be registered. The same happens with single-script applications, if you don't import your views, the application does not see them.

This is because these route and errorhandler decorators do the registration with the blueprint or application at import time.

**Comment by testerman77** [comment]
Got it.Thank you for you reply,and I also found the reason in this address
http://flask.pocoo.org/docs/0.10/patterns/lazyloading/
