### ISSUE TITLE
Gmail says flask app in unsecure

### ISSUE THREAD

**Issue by alybel** [miguelgrinberg/flasky#65]
Hi, 

I can send emails through gmail as described in the book but only when I tell googlemail to accept unsecure apps. What is the proper way to set the gmail account settings such that gmail treats it as secure? 

Thanks!

**Comment by miguelgrinberg** [comment]
Unfortunately Gmail considers "less secure" any application that uses the standard IMAP/POP/SMTP protocols to send/receive emails, so basically any third party email app such as the native email apps in OS X or Windows, Thunderbird, etc. all are going to be considered less secure like the solution I present in the book.

Based on the little information I could find, the way to make an email sending client fully secure is by using OAuth2 authentication. Google created extensions to the email protocols that use OAuth2 instead of the regular authentication mechanisms defined by these protocols. You can find a description of these extensions in the [XOAUTH2](https://developers.google.com/gmail/xoauth2_protocol?hl=en) page.

The bad news is that Flask-Mail and the smtplib package from the Python standard library do not support this XOAUTH2 extension that Google created, so I don't think there is an easy way to do what you ask. I have written an article on my blog regarding the use of the [OAuth protocol](http://blog.miguelgrinberg.com/post/oauth-authentication-with-flask), this article could provide the basis for a solution.

This is mentioned in the book, but I'll repeat it just in case. I use Gmail as an email server because of its widespread availability and simplicity. But Gmail is not a good email server to use in production, it is only intended as a development/testing server. By using Gmail in the book I avoided the tedious and unrelated topic of having to set up your own email server, which you have to do for any kind of production application, Flask or anything else. Back when I wrote the book there were no restrictions for third party apps to access Gmail, I would probably look for other options if I had to write that chapter today.

**Comment by alybel** [comment]
thanks for the clarification!

**Comment by bothwellw** [comment]
Hi Miguel

Thanks for this.

I would like a bit of clarification on why you say "Gmail is not a good email server to use in production" 

Regards
Bothwell

**Comment by miguelgrinberg** [comment]
@bothwellw The Gmail terms have some wording to the effect of being for personal use. Also Gmail implements quotas for the email server, you can't send unlimited amounts of email.

**Comment by bothwellw** [comment]
Many thanks Miguel.

**Comment by sandeepreddy1995** [comment]
hey!miguel i have given access to less secure apps for both my gmail account as iam sending email from one email to another,but still iam getting connection refused error,can you help me in that

**Comment by miguelgrinberg** [comment]
@sandeepreddy1995 it's impossible for me to know without details. Look at the error response that gmail is giving you for clues.
