### ISSUE TITLE
The logic of the confirmation with token route

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#70]
Hi @miguelgrinberg ,

I have a question on the confirmation with token route: 

    @auth.route('/confirm/<token>')
    @login_required
    def confirm(token):
        if current_user.confirmed:
            return redirect(url_for('main.index'))
        if current_user.confirm(token):
            flash('You have confirmed your account. Thanks!')
        else:
            flash('The confirmation link is invalid or has expired.')
        return redirect(url_for('main.index'))

When a new user clicks the link in the email to confirm the email address, the login page is presented with a message "Please log in to access this page.", which is due to @login_required decorator I guess. Only when the new user logs in the message "You have confirmed your account. Thanks!" shows. I prefer the logic as follows: after clicking the confirmation link the email, the message  "You have confirmed your account. Thanks!" shows with the login page presented. I don't know what you think - I tried to take out @login_required and get an error saying anonymous user does not have confirmed attribute. Could you please help? Thanks!!

**Comment by miguelgrinberg** [comment]
Forcing the user to authenticate before the account is marked as confirmed is a security measure. If the user is not able to produce a valid password you certainly do not want to confirm the account, and the only way to find out is to ask for the password first.

The user id is encoded in the token (see the `User.confirm` method), so you could change things so that confirmation is done without the authentication step. You will not be able to use Flask-Login's `current_user` though, you will need to manually load the user whose id is stored in the token, and call the confirm method on that user.

An alternative solution is to automatically log the user in when an account is registered. I do not do that, but if you do the login during registration. Then as long as the browser window is not closed, the registration link will go through without requiring an additional login step.

**Comment by harrywang** [comment]
Thanks a lot for the information! This is very helpful.
